version: '3'

services:
  dev: # ImageName="フォルダ名-dev"のdevの部分
    build: .
    container_name: f0_exp # これがコンテナ名になる。
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    tty: True # 落ちないように
    command: "/bin/bash"
    volumes:
      - .:/home/user/project
    # environment: # これは無くても問題ない
    #   - "NVIDIA_VISIBLE_DEVICES=all"
    #   - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
              - gpu