defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:05d}"
  monitor: "monitor" # 判定用
  mode: "min" # 最大最小設定
  save_top_k : 5
  save_last: False
  auto_insert_metric_name: False

early_stopping:
  monitor: "monitor"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
