# @package _global_

defaults:
  - _self_
  - data: NamineRitsu
  - model: consistency_wavenet
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ./logs/train/runs/2024-06-24_04-04-24/checkpoints/last_epoch.ckpt
