# @package _global_

defaults:
  - _self_
  - data: ddpm_wavenet
  - model: ddpm_wavenet
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2024-06-15_03-47-12/checkpoints/last.ckpt
